import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { build } from "esbuild";
import { randomUUID } from "node:crypto";
import { baseUrlFor } from "./wire.js";
import { validateOps } from "./operations.js";
import type { AppDef } from "./types.js";
export type DuetConfig = { app: string; clientDir?: string; tsconfig?: string; viteConfig?: string };
async function bundle(entry: string, output: string): Promise<string[]> {
  const result = await build({ absWorkingDir: path.dirname(entry), metafile: true, entryPoints: [entry], outfile: output, bundle: true, platform: "node", format: "esm", packages: "external", logLevel: "silent" });
  if (result.warnings.some(w => w.id === "duplicate-object-key")) throw new Error(result.warnings.map(w => w.text).join("\n"));
  return Object.keys(result.metafile!.inputs).map(input => path.resolve(path.dirname(entry), input));
}
const relativeImport = (from: string, to: string): string => {
  const rel = path.relative(from, to).replaceAll(path.sep, "/").replace(/\.tsx?$/, ".js"); return rel.startsWith(".") ? rel : `./${rel}`;
};
async function writeChanged(file: string, text: string): Promise<void> {
  if (await fs.readFile(file, "utf8").catch(() => "") !== text) await fs.writeFile(file, text);
}
export async function generate(cwd = process.cwd(), configFile = "duet.config.ts") {
  const scratch = path.join(cwd, ".duet"); await fs.mkdir(scratch, {recursive: true});
  const configOutput = path.join(scratch, "config.mjs");
  const inputs = await bundle(path.resolve(cwd, configFile), configOutput);
  const config = (await import(`${pathToFileURL(configOutput).href}?t=${randomUUID()}`)).default as DuetConfig;
  if (!config || typeof config.app !== "string") throw new Error("duet.config.ts must default-export { app: './app.ts' }");
  const entry = path.resolve(cwd, config.app);
  const appScratch = path.join(path.dirname(entry), ".duet"); await fs.mkdir(appScratch, {recursive: true});
  const appOutput = path.join(appScratch, "app.mjs");
  inputs.push(...await bundle(entry, appOutput));
  const app = (await import(`${pathToFileURL(appOutput).href}?t=${randomUUID()}`)).app as AppDef;
  if (!app?.id || !app.version || !app.actions) throw new Error("app entry must export a defineApp result as 'app'");
  validateOps(app);
  const directory = path.resolve(cwd, config.clientDir ?? path.join(path.dirname(config.app), "duet"));
  await fs.mkdir(directory, {recursive: true});
  const importPath = relativeImport(directory, entry);
  const comment = "// Generated by duet. Do not edit. Operation types come directly from the app.\n";
  // Remove only our old generated modules; never remove a handwritten file.
  for (const name of ["client.ts", "server.ts"]) {
    const file = path.join(directory, name);
    const previous = await fs.readFile(file, "utf8").catch((error: NodeJS.ErrnoException) => {
      if (error.code === "ENOENT") return "";
      throw error;
    });
    if (previous.startsWith(comment)) await fs.unlink(file);
  }
  await writeChanged(path.join(directory, "browser.ts"), `${comment}import type { app } from ${JSON.stringify(importPath)};\nimport { createClient } from "duet-mcp/react";\nimport connection from "./connection.js";\nconst client = createClient<typeof app>({ id: connection.id, version: connection.version });\nexport const { useDoc, getDoc, getObserverID, disposeObserver } = client;\n`);
  await writeChanged(path.join(directory, "connection.ts"), `${comment}export default ${JSON.stringify({ url: baseUrlFor(app.id, app.port), id: app.id, version: app.version }, null, 2)};\n`);
  await writeChanged(path.join(directory, "node.ts"), `${comment}import type { app } from ${JSON.stringify(importPath)};\nimport { createClient } from "duet-mcp/server";\nimport connection from "./connection.js";\nconst client = createClient<typeof app>(connection);\nexport const { getDoc, getObserverID, disposeObserver } = client;\n`);
  return { config, directory, appOutput, entry, inputs };
}
