import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import type { Server } from "node:http";
import { serve } from "@hono/node-server";
import { chromium } from "playwright";
import { DocStore } from "../duet/doc.js";
import { createHttpApp } from "../duet/http.js";
import { app } from "../template/app.js";

test("browser preserves a draft through external edits and publishes the rendered revision", async(t)=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),"duet-browser-"));
  const store=new DocStore(app,dir);
  const server=serve({fetch:createHttpApp(app,()=>store).fetch,port:0,hostname:"127.0.0.1"}) as Server;
  t.after(async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));fs.rmSync(dir,{recursive:true,force:true});});
  const browser=await chromium.launch({headless:true});
  t.after(async()=>{await browser.close();});
  if (!server.listening) await new Promise<void>(r=>server.once("listening",r));
  const port=(server.address() as {port:number}).port;
  const page=await browser.newPage();
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${port}`);
  await page.locator("#text").fill("human draft");
  store.run("set_text",{baseRevision:store.revision,text:"llm update"},"llm");
  await page.waitForFunction(()=>document.querySelector("#shot")?.textContent==="llm update");
  assert.equal(await page.locator("#text").inputValue(),"human draft");
  await page.getByRole("region",{name:"Shared note"}).getByRole("button",{name:"Apply",exact:true}).click();
  await page.getByRole("alert").waitFor();
  assert.equal(store.snapshot("human").doc.text,"llm update");
  assert.equal(await page.locator("#text").inputValue(),"human draft");
  await page.getByRole("button",{name:"Review and apply draft",exact:true}).click();
  await page.waitForFunction(()=>document.querySelector("#shot")?.textContent==="human draft");
  assert.equal(store.snapshot("human").doc.text,"human draft");
  assert.equal(await page.locator("html").getAttribute("data-duet-revision"),store.revision);
  // Verify both DOM capture and the screenshot endpoint.
  const shot=await page.locator("#shot").screenshot();assert.ok(shot.byteLength>100);
  const previous=process.env.DUET_SHOT_ORIGIN;
  process.env.DUET_SHOT_ORIGIN=`http://127.0.0.1:${port}`;
  t.after(async()=>{
    if(previous===undefined)delete process.env.DUET_SHOT_ORIGIN;else process.env.DUET_SHOT_ORIGIN=previous;
    const holder=globalThis as unknown as {__duetShot?:{browser:{close():Promise<void>}}};
    await holder.__duetShot?.browser.close();
  });
  const rendered=await fetch(`http://127.0.0.1:${port}/api/shot`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});
  assert.equal(rendered.status,200);
  const image=await rendered.json() as {data:string};
  assert.equal(Buffer.from(image.data,"base64").subarray(1,4).toString(),"PNG");
  const controls=page.getByRole("region",{name:"Design settings"});
  await controls.getByLabel("Heading",{exact:true}).fill("Shared canvas");
  await controls.getByLabel("Outline",{exact:true}).check();
  await controls.getByLabel("Accent color").selectOption("blue");
  await controls.getByLabel("Dot grid",{exact:true}).uncheck();
  await controls.getByRole("button",{name:"Apply",exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('[aria-label="Design settings"] [role="status"]')?.textContent==="Saved");
  assert.equal(store.snapshot("human").doc.settings.caption,"Shared canvas");
  assert.equal(store.snapshot("human").doc.settings.style,"outline");
  assert.equal(store.snapshot("human").doc.settings.grid,false);
  const canvas=page.getByLabel("Canvas: move and resize the box");
  const drag=async(x:number,y:number,dx:number,dy:number,external=false)=>{
    const r=(await canvas.boundingBox())!;
    const px=r.x+x*r.width/720,py=r.y+y*r.height/480;
    await page.mouse.move(px,py);await page.mouse.down();
    await page.mouse.move(px+dx*r.width/720,py+dy*r.height/480,{steps:4});
    if(external)store.run("set_text",{baseRevision:store.revision,text:"during drag"},"llm");
    await page.mouse.up();
  };
  await drag(300,200,40,20);
  await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('[aria-label="Box x"]')?.value==="200");
  await page.waitForFunction(()=>!document.querySelector('canvas')?.parentElement?.querySelector('[role="status"]'));
  assert.equal(store.snapshot("human").doc.box.x,200);
  for(const corner of ["se","nw","ne","sw"]) {
    const b=store.snapshot("human").doc.box;
    await drag(corner.includes("w")?b.x:b.x+b.width,corner.includes("n")?b.y:b.y+b.height,corner.includes("w")?-10:10,corner.includes("n")?-10:10);
    await page.waitForFunction(()=>!document.querySelector('canvas')?.parentElement?.querySelector('[role="status"]'));
    assert.equal(store.snapshot("human").doc.box.width,b.width+10);
    assert.equal(store.snapshot("human").doc.box.height,b.height+10);
  }
  const before=store.snapshot("human").doc.box;
  await drag(before.x+30,before.y+30,20,20,true);
  await page.getByRole("alert").waitFor();
  assert.deepEqual(store.snapshot("human").doc.box,before);
  await page.getByRole("button",{name:"Review and apply draft",exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('[role="alert"]'));
  assert.equal(store.snapshot("human").doc.box.x,before.x+20);
  const waitForCanvasSize = () => page.waitForFunction(() => {
    const canvas = document.querySelector("canvas")!;
    return Math.abs(canvas.width - (canvas.getBoundingClientRect().width - 2) * devicePixelRatio) < 2;
  });
  await page.setViewportSize({width:1440,height:1150});
  await waitForCanvasSize();
  const artifactDir = process.env.DUET_TEST_ARTIFACT_DIR;
  if (artifactDir) fs.mkdirSync(artifactDir, {recursive:true});
  await page.screenshot({...(artifactDir ? {path:path.join(artifactDir,"duet-studio-desktop.png")} : {}),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await waitForCanvasSize();
  await page.screenshot({...(artifactDir ? {path:path.join(artifactDir,"duet-studio-mobile.png")} : {}),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  assert.deepEqual(errors,[]);
});
